---
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get install gnupg-curl
      - run: >-
          gpg
          --keyserver hkps://keys.gentoo.org
          --recv-keys
          534E4209AB49EEE1C19D96162C44695DB9F6043D
          E1D6ABB63BFCFB4BA02FDF1CEC590EEAC9189250
      - run: make image test

  push:
    machine: true
    steps:
      - checkout
      - run: make tag
      - run: docker push adborden/gentoo


workflows:
  version: 2
  commit:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only:
                - master
